#!/bin/bash
# ---------------------------------------------------------------------------
# lectl
# Script to check issued certificates by Let's Encrypt in
# CTL (Certificate Transparency Log) using https://crt.sh
#
# Note: crt.sh is property of COMODO CA Limited 2015-2017

# Author: sahsanu

# DOWNLOAD lectl
# You'll find last lectl version at https://github.com/sahsanu/lectl

# LICENSE:
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

# HELP:
#U Usage:
#U
#U lectl [-h|--help] [-v|--version] [-l|--extraline] [-s|--sans] [-e|--expired] [-u|--utc] domain
#U
#H Options:
#H
#H -h | --help      [Default: false] shows the help file.
#H
#H -v | --version   shows the script version.
#H
#H -l | --extraline [Default: false] adds extra line separator between found
#H                  certificates (when there are several certs with several
#H                  sans adding this extra line it's easier to read the output).
#H
#H -s | --sans      [Default: false] shows all domains included in the
#H                  certificate as SANs. If you don't use this option you will
#H                  only see the Common Name.
#H
#H -e | --expired   [Default: false] shows all certs issued for the specified
#H                  domain, including the certs that are already expired.
#H
#H -u | --utc       [Default: false] shows the dates in UTC (GMT) instead of
#H                  your machine time zone.
#H
#H -m               [Default: 100] searchs for more or less than 100 certificates
#H                  per domain OR subdomain. It means that if for example you use
#H                  option -m25 you could receive an output of max 50 certs (25 for
#H                  the domain and 25 for *.domain).
#H                  If this option is not used, lectl searchs only for last 100
#H                  certificates. If the option is used it searches by default
#H                  for last 1000 certificates.
#H                  If you want to search for more or less certificates, append
#H                  the number after the option with no spaces (Ex: -m500). If
#H                  you specify a number, then the option must be specified
#H                  independently.
#H                  Wrong: lectl -seulm500 domain.tld
#H                  Good: lectl -seul -m500 domain.tld
#H
#H
#H Examples:
#H
#H     lectl letsencryt.org
#H     lectl -s -e -u -l letsencryt.org
#H     lectl -seulm letsencryt.org
#H     lectl -lumse letsencryt.org
#H     lectl -su --extraline letsencryt.org
#H     lectl -u letsencryt.org -esm
#H     lectl -seul -m500 letsencryt.org
#H     ...and so on
#H
# CHANGELOG:
# 2016-Feb-10: Created (v0.1)
# 2016-Mar-24: Public release with many fixes (v0.2)
# 2016-Mar-25: Add support to new certificate authority X3 (v0.3)
# 2016-Mar-27: Rate limits have changed from 5 per 7 days to 20 per 7 days (v0.4)
# 2016-Mar-28: Add support to Let's Encrypt authorities X2 and X4 (v0.5)
# 2016-Apr-04: Fix, if no domain is found in crt.sh the script didn't perform the housekeeping (v0.6)
# 2016-Jun-04: Fix, add env language variables pointing to C locale so date command output is in english (v0.7)
# 2016-Oct-26: Fix, crt.sh web page changed the html of their pages so lectl was not working at all (v0.8)
# 2016-Oct-26: Enhanced, CA IDs assigned by crt.sh to Let's Encrypt (X1, X2, X3...) are not harcoded anymore, they are fetched dynamically from crt.sh web page (v0.8)
# 2017-Jun-11: Fix, if the number of certificates to display is 100 or more the columns were not displayed correctly (v0.9)
# 2017-Sep-15: Enhanced, added option -m to search for more (or less) than 100 (default option) certificates. This option closes issue https://github.com/sahsanu/lectl/issues/2 (v0.10)
# 2017-Sep-15: I want to thank Github User spikebike (https://github.com/spikebike) for the tip to be able to search more or less than 100 certificates on crt.sh site (v0.10)
# 2017-Oct-06: Enhanced, utilities are defined in variables so it is easier to change them if you are using for example OS X and want to change date by gnu date (ggdate) (v0.11)
# 2017-Oct-06: Fix, if maxnumberofcerts is less than ratelimit there is no need to show any advice because it won't be accurate (v0.11)
# TODO:
# Clean up and comment the code
# Create auto-update version (comming soon)

#Variables for utilities
_date=date #Change date by gdate if you are using homebrew on OS X
_sed=sed   #Change sed by gsed if you are using homebrew on OS X
_grep=grep
_curl=curl
_awk=awk
_cat=cat
_sort=sort
_column=column
_tail=tail
_tr=tr
_wc=wc

# Script version/name variables
version='0.11'
scriptname='lectl'
lastmodification='2017-October-06'
checknewversion=1
forceupgrade=0
maxnumberofcerts=100

#Export env language variables to use C locale
export LANG=C
export LANGUAGE=C
export LC_ALL=C

_selfupgrade() {
echo ""
}

_checkcommands() {
for i in $*;do
    if ! command -v "$i" &>/dev/null ;then
    echo "Command \"$i\" not found."
    echo "Sorry, I can't continue, I need \"$i\" to run."
    exit 1
    fi
done
}

_checkcommands "$_curl $_awk $_grep $_sed $_cat $_date $_sort $_column $_tail"

_checknewversion() {
    if [ $checknewversion = 1 ];then
        lectllastsource=$($_curl -sSk "https://raw.githubusercontent.com/sahsanu/lectl/master/lectl")
    fi
}

_showversion() {
    echo "${scriptname} $version (${lastmodification})"
    printf '\n'
}

_showversion

utc=""
domain=""
extraline=""
showsans="0"
columnsans=""
showexpired="1"
expired='&exclude=expired'
nonexpired="non expired "
ratelimit='20'

# Define message functions
_echoerr()  { echo "Error: $@" >&2; }
_echowarn() { echo "Warning: $@"; }
_echoinf()  { echo "Info: $@"; }

# Function to check error on previous command
_checkerror() {
    rc=$?
    if [ "${rc}" -ne 0 ]; then
        _echoerr "${1}"
        _echoerr "Return code was: ${rc}"
        printf '\n'
        _housekeeping
        exit ${rc}
    fi
}

# No comment[s]
_plural() {
    if [ "$1" -eq "1" ] || [ "$1" -eq "-1" ];then
        printf ''
    else
        printf 's'
    fi
}

# Help and usage functions
_showusage() {
    usage=$($_grep '^#U' "$0")
    _checkerror "Ups, Where is my help?, Did you modified the comments of my script?"
    $_sed 's/#U//' <<< "${usage}"
}

_showhelp() {
    _showusage
    help=$($_grep '^#H' "$0")
    _checkerror "Ups, Where is my help?, Did you modified the comments of my script?"
    $_sed 's/#H//' <<< "${help}"
}

# Clean the house
_housekeeping() {
    if [ -d "${tempdir}" ];then
        rm -rf "${tempdir}"
    fi
}

# Take care of signals
_trap_exit() { # Handle trapped signals
  case $1 in
    INT)
      _echoerr "${scriptname} has been interrupted by user"
      _housekeeping
      exit 100
      ;;
    TERM)
      _echoerr "${scriptname} terminated"
      _housekeeping
      exit 101
      ;;
    *)
      _echoerr "Terminating ${scriptname} on unknown signal"
      _housekeeping
      exit 102
      ;;
  esac
}

# Trap signals
trap "_trap_exit INT" INT
trap "_trap_exit TERM" TERM HUP

_parsemorecerts() {
    if [ "$1" == "" ]; then
        maxnumberofcerts="100"
        return
    fi
    if [ "$1" == "-m" ]; then
        maxnumberofcerts="1000"
        return
    else
        _tmp_maxnumberofcerts=$(echo "$1" | $_tr -d '\-m')
        re='^[0-9]+$'
        if ! [[ $_tmp_maxnumberofcerts =~ $re ]] ; then
           _echoerr "Option for -m is not a number"
           printf '\n'
           exit 150
        else
           maxnumberofcerts=$_tmp_maxnumberofcerts
           return
        fi
    fi
}

# Parse options
_parseoptions() {
    if [ "$#" -gt "0" ];then
        while [ -n "$1" ]; do
            case $1 in
                    -h | --help) _showhelp; exit ;;
                     -u | --utc) utc="-u" ;;
                      -s|--sans) showsans='1'; columnsans=';SANs' ;;
                   -e|--expired) showexpired="0"; expired=''; nonexpired='' ;;
                 -l|--extraline) extraline='\n' ;;
                 -v | --version) exit ;;
                            -m*) _parsemorecerts "$1" ;;
                       -* | --*) _echoerr "Unknown option $1"; _showusage; exit 1 ;;
                              *) domain="${1}" ;;
            esac
            shift
        done
    else
        _echoerr "You MUST specify a domain name."
        printf '\n'
        exit 1
    fi

    if [ -z "${domain}" ];then
        _echoerr "You MUST specify a domain name."
        printf '\n'
        exit 1
    else
        echo "${domain}" | $_grep -E '^[a-zA-Z0-9\.-]+\.[A-Za-z]{2,}$' &>/dev/null
        _checkerror "Seems the specified domain ${domain} is not valid"
    fi
}

while [ -n "$1" ];do
    param=$(printf -- "$1" | tr '[:upper:]' '[:lower:]')
    if $_grep -E '^-[a-z]{2,}' <<< $param &>/dev/null ;then
        for i in $(printf -- "$param" | $_sed 's/-//' | $_grep -o .); do options="$options -$i";done
        shift
    else
        options="$options $param"
        shift
    fi
done

_parseoptions $options


# Define temp dir and tempifile
tempdir=".${scriptname}.$$.tmp"
if [ ! -d "${tempdir}" ];then
    mkdir "${tempdir}"
fi
tempfile="${tempdir}/${domain}.$$.rl.tmp"

# Let's go
echo "$($_date +"%Y/%B/%d %H:%M:%S") - Checking certs for ${domain}"
echo " "

#Get CA ids assigned to Let's Encrypt by crt.sh
caidsle=$($_curl -sSk "https://crt.sh/?CAName=%25s+Encrypt%25")
_checkerror "Failed to retrieve Lets Encrypt CA ids"

caidsle=$(echo "$caidsle" | $_awk -F '=|"|<' '/caid/ {print $6}')
_checkerror "Failed to split Lets Encrypt CA ids"

# Define crt.sh url
crturldomainid="https://crt.sh/?id="
numberofcerts="&p=1&n=${maxnumberofcerts}"

for caid in ${caidsle};do
# Get issued certificates for domain and subdomains (X1, X2, X3, X4, etc.)
    $_curl -sSk "https://crt.sh/?Identity=${domain}&iCAID=${caid}${expired}${numberofcerts}" >> "${tempfile}" 2>/dev/null
    _checkerror "Failed to retrieve https://crt.sh/?Identity=${domain}&iCAID=${caid}${expired}${numberofcerts}"

    $_curl -sSk "https://crt.sh/?Identity=%.${domain}&iCAID=${caid}${expired}${numberofcerts}" >> "${tempfile}" 2>/dev/null
    _checkerror "Failed to retrieve https://crt.sh/?Identity=%.${domain}&iCAID=${caid}${expired}${numberofcerts}"
done

# Put certificates found in variable
certsfound=$($_grep -A3 '?id=' "${tempfile}" | $_sed ':a;N;$!ba;s/>\n//g'| $_tr -d ' ')

# Sorting output and removing duplicates so last cert is the first in the list
certsfound=$(echo "$certsfound" | $_sed 's/^.*id=//' | $_sort -run | $_sed 's/^/<TD><Ahref="?id=/')

# Count certificates
numberofcerts=$(echo "${certsfound}" | $_grep '>CN=' | $_wc -l)
numberofcerts=$(echo "${numberofcerts}" | $_tr -d ' ')

if [ "${numberofcerts}" -le 0 ];then
    _echoinf "I've not found any certificate for the domain ${domain}"
    printf '\n'
    _housekeeping
    exit 0
fi

for i in $(echo "${certsfound}");do
    id=$(echo "$i" | $_awk -F'id=|>|"' '{print $4}')
    domainid=$(echo "$i" | $_awk -F'CN=|>|<' '{print $17}')

    $_curl -sS "${crturldomainid}${id}" > "${tempfile}.${id}" 2>/dev/null
    _checkerror "Failed to retrieve ${crturldomainid}${id}"

    validfrom=$($_sed 's/Not&nbsp;Before:/\r\nBxexfxoxrxex:/g' "${tempfile}.${id}" | $_awk -F'<BR>' '/^Bxexfxoxrxex:/ {print $1}' | $_sed 's/Bxexfxoxrxex:&nbsp;//g' | $_sed 's/&nbsp;/ /g')
    validfrom=$($_date ${utc} -d "${validfrom}" +'%Y-%b-%d %H:%M %Z')

    validto=$($_sed 's/Not&nbsp;After&nbsp;:&nbsp;/\r\nAxfxtxexrx:/g' "${tempfile}.${id}" | $_awk -F'<BR>' '/^Axfxtxexrx:/ {print $1}' | $_sed 's/Axfxtxexrx://g' | $_sed 's/&nbsp;/ /g')
    validto=$($_date ${utc} -d "${validto}" +'%Y-%b-%d %H:%M %Z')

    expiresin=$(($(($($_date ${utc} -d "$(echo "${validto}" | $_awk -F'-| ' '{print $2,$3,$4,$5,$1}')" +"%s") - $($_date ${utc} +"%s"))) / 86400))
    expiresin="${expiresin} day$(_plural ${expiresin})"

    if [ "${showsans}" -eq "1" ]; then
        SANS=$($_sed 's/DNS:/\r\nDNS:/g' "${tempfile}.${id}" | $_awk -F'<BR>' '/^DNS:/ {print $1}' | $_sed 's/DNS:/ ; ; ; ; ;/g' | $_sed ':a;N;$!ba;s/\n/\\n/g' | $_sed 's/ ; ; ; ; ;//')
        partialresult=$(printf "%s;%s;%s;%s;%s;%s" "$id" "$domainid" "$validfrom" "$validto" "$expiresin" "$SANS")
        result="${result}\n${partialresult}${extraline}; ; ; ; ;\n"
    else
        partialresult=$(printf "%s;%s;%s;%s;%s;%s" "$id" "$domainid" "$validfrom" "$validto" "$expiresin")
        result="${result}\n${partialresult}${extraline}; ; ; ;\n"
    fi
done

finalresult=$result

echo "I have found ${numberofcerts} ${nonexpired}certificate$(_plural $numberofcerts) (max number of certs searched: ${maxnumberofcerts}) for domain ${domain} and its subdomains *.${domain}"
printf '\n'
echo -e "CRT ID;DOMAIN (CN);VALID FROM;VALID TO;EXPIRES IN${columnsans}\n${finalresult}" | $_column -t -s ';'

count=0
finalresult=$(echo "${finalresult}" | $_sed 's/\\n\\n/TRISCADEICADELICA/g' | $_sed 's/\\n//g' | $_sed 's/TRISCADEICADELICA/\n/g' | $_tr ' ' '_')

for i in $(echo "${finalresult}" | $_awk -F';' '{print $3}');do
    rightnow=$($_date ${utc} +'%s')
    i=$(echo "$i" | $_tr '_' ' ')
    converteddate=$(echo "$i" | $_awk -F'-| ' '{print $2,$3,$4,$5,$1}')
    certdate=$($_date $utc -d "$converteddate" +'%s')
    daystoexpire=$(((${rightnow}-${certdate})/(60*60*24)))

    if [ "${daystoexpire}" -lt "7" ] && [ "${count}" -lt "${ratelimit}" ];then
        count=$((count+1))
        dentrode="${dentrode}\n${converteddate}"
    fi
done

#If maxnumberofcerts is less than ratelimit there is no need to show any advice because it won't be accurate
if [ $maxnumberofcerts -ge $ratelimit ]; then
    remaining=$((${ratelimit}-count))
    if [ $remaining -le 0 ];then
        lastcert=$(echo -e "${dentrode}" | $_tail -n1 )
        next=$($_date ${utc} -d "${lastcert}+7 days 1 minute" +'%A %Y-%b-%d %H:%M:%S %Z')
        if [ -z "${extraline}" ];then echo " ";fi
            echo "Sorry, you can't issue any certificate, you already issued $count certificate$(_plural $count) on last 7 days"
            echo "You could issue next certificate on $next"
            printf '\n'
            echo "Note 1: Keep in mind that if ${domain} is included in PSL (Public Suffix List) the rate limit could only be applied to your subdomain instead of your domain."
            echo "Note 2: Right now Let's Encrypt is implementing a new feature so if you renew the exact cert (with the same FQDNs) the rate limit could not apply to your domain if you try to renew it."
            printf '\n'
        else
            if [ -z "${extraline}" ];then echo " ";fi
            echo "You have issued ${count} certificate$(_plural ${count}) in last 7 days so you could issue ${remaining} more certificate$(_plural ${remaining}) now."
            printf '\n'
        fi
else
    printf '\n'
fi

_housekeeping
